name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        activate-environment: youtube-wechat
    
    - name: Install package
      shell: bash -l {0}
      run: |
        conda activate youtube-wechat
        # Create a symbolic link to make imports work
        mkdir -p youtube_wechat
        ln -sf $(pwd)/src youtube_wechat/src
        # Install the package
        pip install -e .
    
    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate youtube-wechat
        # Add the current directory to the Python path
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m unittest discover tests/
